language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    - { os: linux, env: PYTHON_VERSION=3.4 }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: osx, env: PYTHON_VERSION=3.5 }

env:
  global:
  - ENCRYPTION_LABEL: "898e0934cf65"
  - COMMIT_AUTHOR_EMAIL: "janos.sallai@vanderbilt.edu"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - git fetch -t
  - source devtools/travis-ci/install_conda.sh
  - conda config --add channels omnia
  - conda config --add channels bioconda
  - conda config --add channels glotzer
  - conda config --add channels mosdef

script:
  - conda build devtools/conda-recipe
