package:
  name: foyer-dev
  version: !!str 0.1.0.dev0

build:
  noarch_python: True

requirements:
  build:
    - python

  run:
    - python
    - parmed
    - networkx
    - oset
    - six
    - openmm
    - plyplus

test:
  requires:
    - pytest
  commands:
    - py.test -v --tb=short --pyargs foyer

about:
  home: http://imodels.github.io/foyer
  license: MIT
  summary: Atomtyping and forcefield applying.
